module.exports = {
  name: 'Central Bucks',
  state: 'PA',
  county: 'Bucks',
  schools: {
    elementary: [
      'Barclay',
      'Bridge Valley',
      'Buckingham',
      'Butler',
      'Cold Spring',
      'Doyle',
      'Gayman',
      'Groveland',
      'Jamison',
      'Kutz',
      'Linden',
      'Mill Creek',
      'Pine Run',
      'Titus',
      'Warwick',
    ],
    middle: ['Lenape', 'Tamanend', 'Unami', 'Holicong', 'Tohickon'],
    high: ['East', 'South', 'West'],
  },
};
